config/routes.rb
Rails.application.routes.draw do
  
  get 'buy/buyitems'
  get '/buyitems' => 'buy#buyitems'
  
  get 'buy/emptycart'
  get '/emptycart' => 'buy#emptycart'
  
  resources :profiles
  devise_for :users
  
  root 'items#index'
  get 'cart/index'

  get 'site/about'

  get 'site/contact'
  
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  
  get '/Admin' => 'user#admin_login'
  get '/logout' => 'user#logout'
  
  get '/cart' => 'cart#index'

  
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
    
    def self.search(search)
        where("description LIKE ?", "%#{search}%")
    end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def after_sign_in_path_for(resource)
        "/signedinuserprofile"
       
    end
end

app/controllers/buy_controller.rb
class BuyController < ApplicationController
  def buyitems

    
  
      session[:cart] ={}
     

    
  end
  
  def emptycart
    
    session[:cart] ={}
   
  end
end



  

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    #get the ID of the product
    id = params[:id]
    
    #if the cart is already created, used the existing, else create a blank
    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart] ={}
      cart = session[:cart]
    end
    
    #if the product has already been added to the cart, increment value, otherwise set value to 1
    if cart[id] then
      cart[id] =cart[id]+1
    else
      cart[id]=1
    end
    
    #redirect to the cart display page
    redirect_to :action => :index
  end
  
  def clearCart
    #set the session variable to nil and redirect
    session[:cart] = nil
    redirect_to :action => :index
  end

  
  def buyitems
      @quantity_in_stock = Inventory.find (params[cart_item][:id])
      @cart = find_cart
      @cart.new_quantity(@inventory.id, params[:cart_item][:quantity])
    
  end
  
  
  
  def index
    #if there is a cart, pass it to the page for display otherwise pass an empty value
    if session[:cart]then
      @cart=session[:cart]
    else
      @cart={}
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_admin, :only => [:edit, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    
    if @items= Item.search(params[:search]).order("created_at DESC")
    else
      @items = Item.all.order('created_at DESC')
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def ensure_admin
    unless current_user && current_user.admin?
     render :text => "Access Error Message", :status => :unauthorized
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
    
        params.require(:item).permit(:title, :category, :description, :cost_price, :selling_price, :image_url, :brand, :supplier, :qty_in_stock, :order_no, :size, :features, :specification, :rider_position, :rider_profile)
      
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @profile.user_id = current_user.id
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile}
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def signedinuserprofile
    profile = Profile.find_by_user_id(current_user.id)
    if profile.nil?
      redirect_to "/profiles/new"
    else
      @profile = Profile.find_by_user_id(current_user.id)
      redirect_to "/profiles/#{@profile.id}"
    end
  end
  





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    #after_sign_in_path_for is called by devise
    def after_sign_in_path_for(user)
        "/signedinuserprofile" #provide the path for user's profile
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def login
    end
    
    def admin_login
        session[:login] =1
        session[:cart] =nil;
        flash[:notice] = "Admin Login Successful!"
        redirect_to :controller =>:items
    end
    
    def logout
        session[:login] =nil
        session[:cart] =nil;
        flash[:notice] = "You have successfully logged out."
        redirect_to :controller =>:items
    end
    
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/buy/buyitems.html.erb
<h1>Thank you for your purchase</h1>
    
<p>    </p>
    
    
<h1>Your Purchase is complete</h1>

<br>

app/views/buy/emptycart.html.erb
<h1>Your Cart is Empty</h1>
    

    

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<% if @cart.empty? %>
<p> Your Cart is empty.</p>
<%end%>

<% total = 0 %>

<table class="cart">
<tr>
    <td class="legend"></td>
    <td class="legend">Item</td>
    <td class="legend">Price</td>
    <td class="legend">Qty</td>
    <td class="legend">Total</td>
    <td class="legend">Qty In Stock</td>
</tr>

<% @cart.each do |id,quantity | %>
<% item = Item.find_by_id(id) %>
<tr>
    <td>
        <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
            
        </div>
    </td>
    
    <td class="title"><%=link_to item.title, item %></td>
    <td class="cost"><%=number_to_currency(item.cost_price) %></td>
    <td class="quantity"><%= quantity %><br></td>
    <td class="price"><%= number_to_currency(quantity*item.cost_price, :unit =>"Eur") %></td>
    <td class="qty_in_stock"><%= link_to item.qty_in_stock, item %></td>
   
</tr>
<% total += quantity *item.cost_price %>
<% end %>

<tr>
    <td colspan ="4">
    <div class="total"><%=number_to_currency(total, :unit => "Eur") %> Total</div>
    </td>
    <td>
    <div class="price"><%=number_to_currency(total, :unit => "Eur") %></div>
    </td>
</tr>
</table>

<p> 
<%= link_to 'Continue Shopping', :controller => :items %></p>




<a href="/buyitems">Proceed to Checkout</a>

<a href="/emptycart">Empty Cart</a>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :cost_price %><br>
    <%= f.text_field :cost_price %>
  </div>
  <div class="field">
    <%= f.label :selling_price %><br>
    <%= f.text_field :selling_price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :qty_in_stock %><br>
    <%= f.number_field :qty_in_stock %>
  </div>
  <div class="field">
    <%= f.label :order_no %><br>
    <%= f.text_field :order_no %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :features %><br>
    <%= f.text_field :features %>
  </div>
  <div class="field">
    <%= f.label :specification %><br>
    <%= f.text_field :specification %>
  </div>
  <div class="field">
    <%= f.label :rider_position %><br>
    <%= f.text_field :rider_position %>
  </div>
  <div class="field">
    <%= f.label :rider_profile %><br>
    <%= f.text_field :rider_profile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p class="search"><%= form_tag(items_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
  <% submit_tag "Search" %>
<% end %>
</p>
  

<h1>Product Catalogue</h1>
<br>
<table class="catalog">
  
  <% @items.each do |item| %>
  <tr>
    <td>
      <div class = "image">
        <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
        
      </div>
      </td>
      <td>
      <div class="title">
        <%= link_to item.title, item %>
      </div>
      
      <div class="description">
      <%=h item.description %>
      </div>
      <div class="price">
        <%= number_to_currency(item.cost_price, :unit => "Euro") %>
        
      </div>
      <div class="links">
        
        <% if current_user.admin? %>

        <%= link_to 'Edit', edit_item_path(item) %> |
        <%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %>
        <% else %>
        <a href="/cart/<%= item.id %>">Add to Cart</a><br><br>
      
        
        <% end %>
        
        
      </div>
      
    </td>
    
    
  </tr>
  <%end%>
</table>

<% if current_user.admin? %>
<p><%= link_to 'New Item', new_item_path %></p>

<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Cost price:</strong>
  <%= @item.cost_price %>
</p>

<p>
  <strong>Selling price:</strong>
  <%= @item.selling_price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @item.supplier %>
</p>

<p>
  <strong>Qty in stock:</strong>
  <%= @item.qty_in_stock %>
</p>

<p>
  <strong>Order no:</strong>
  <%= @item.order_no %>
</p>

<p>
  <strong>Size:</strong>
  <%= @item.size %>
</p>

<p>
  <strong>Features:</strong>
  <%= @item.features %>
</p>

<p>
  <strong>Specification:</strong>
  <%= @item.specification %>
</p>

<p>
  <strong>Rider position:</strong>
  <%= @item.rider_position %>
</p>

<p>
  <strong>Rider profile:</strong>
  <%= @item.rider_profile %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div id="header">
    
    <h2></h2>
    <h2 align="center">Celtic Bikes Online</h2>
    <h2></h2>
    <h2 align="center">Ireland's Premier Bike Retailer</h2>
    <h2 align="center">Online Store Open 24 7</h2>
    
    
  </div>
  <div id="menu">
    <div id ="navbar">
      <ul>
        <li><a href="/items">Products</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact Us</a></li>
        <li><a href="/users/sign_in">Login</a></li>
        <li><a rel="nofollow" data-method="delete" href="/users/sign_out">Logout</a></li>
        <li><a href="/cart">Cart</a></li>
        
      </ul>
    </div>
  </div>
  
  <div id="container">
    <div id="content">
      <p class="notice"> <%=flash[:notice] %></p>
      <p class="alert"> <%= flash[:alert] %></p>
      <%=yield %>
      
      <% if user_signed_in? %>
      <div>Signed <%= current_user.email %> (<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>)</div>
      <% else %>
      <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_registration_path %>
      <% end %>
   <!--   
    </div>
    <div id="first-column">
      <div class = "loginbox">
        <h2 class="BoxHeaders">Login Here...</h2>
        
      </div>
      <div class="searchbox">
        <h2 class="BoxHeaders">Search Catalogue</h2>
        
      </div>
    </div>
    -->
  </div>
  <div id="footer">
    <h6 class="footertext">&copy; Celtic Cycles &trade; 2017</h6>
  </div>
  


</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/site/about.html.erb
<h1 align="center">Celtic Bikes Online</h1>
<!--<p>Find me in app/views/site/about.html.erb</p>-->

<!--<p align="center">Our History</p1>-->

<h>Our Beginnings</h><p>
Celtic Bikes Online began its story, over 3 weeks ago, in 2017. Ciaran, 
upon completion of his Hdip in Computer Science, commenced trading in partnership with Aidrus.
Shortly after this, they developed an e-commerce website and began online trading, and together
with their dedicated staff built the business into Ireland's most well known online Cycle Store.</p>

<h>Celtic Bikes Online Today</h><p>
Today, The Celtic Bikes Online resides at The Celtic Bikes Building where it delivers an unrivaled 
cycle shopping experience. Our brand new store carries all the major brands. We are an official dealer of Raleigh, Koga and Trek.</p>


<h>Aidrus</h>
<p><img src="/assets/Site/aidrus.jpg" style="width:280px;height:228px;"></p>


<h>Ciaran, the founder of Celtic Bikes Online</h>
<p><img src="/assets/Site/background.jpg" style="width:304px;height:228px;"></p>

app/views/site/contact.html.erb
<h1 align="center">Our Location & Contact Details</h1>
<p><img src="/assets/Site/bikeshop.jpg" style="width:280px;height:228px;"></p>
<!--<p>Find me in app/views/site/contact.html.erb</p>-->
<p1>Our address is:</p1>
Celtic Bikes,
Unit 6,
Kimmage IDA,
Kimmage,
Dublin.</p>

<p1>Our Email is: celticbikes@gmail.com</p1>
<p><p1>Our Contact Numbers: 086 1777777, 086 1666666, 021 123455</p1></p>
<p1></p1>
<h1 align="center">Our Opening Hours</h1>
<p><img src="/assets/Site/open247.jpg" style="width:280px;height:228px;"></p>

<p1> Our store is open Monday to Sunday 09:00 till 22:00</p1>
<p><p1>Our online store is open 24:7 </p1></p>